### ISSUE TITLE
"make install" does not install config files, and installs VERSION into a wrong locaton

### ISSUE THREAD

**Issue by dimpase** [libsemigroups/HPCombi#15]
I install HPCombi separately,  with 
`cmake -DCMAKE_INSTALL_PREFIX=/foo/bar && make && make install`, 
and it does not put anything into `$prefix/lib/cmake/` - which is the location needed by `cmake` to do package discovery.
 It also doesn't install `hpcombi.pc`, even though you have the template `hpcombi.pc.in` - and this prevents `pkg-config` usage for version discovery, too.

You do copy `VERSION` into `$prefix/` - but this is  making no sense; note that `$prefix`, i..e. what you specify with `-DCMAKE_INSTALL_PREFIX=...` is typically something like `/usr/local` placing a file named `VERSION` right there makes no sense.

**Comment by hivert** [comment]
This should be fixed in the upcomming 1.0.0 release.
