### ISSUE TITLE
Move to C+17 and remove the stuff in HPCombi that is obsolete

### ISSUE THREAD

**Issue by james-d-mitchell** [libsemigroups/HPCombi#25]
This includes:

- [x] experimental `lcm`
- [x] constexpr checks and macro in CMakeLists.txt `HPCOMBI_CONSTEXPR_FUN_ARGS` + `HPCOMBI_CONST_EXPR`, 
- [x]  `ConstFun`, `constexpr` lambdas, 
- [x] ~~`TPUBuild`, inside `epu.hpp`~~

**Comment by hivert** [comment]
For reference, I don't think `TPUBuild` is obsolete. I serve as various constructor (in particular constexpr) for epu8 which is not a class and can't have a constructor.

**Comment by james-d-mitchell** [comment]
This is now complete in the simde branch!
