### ISSUE TITLE
Things to finalise before releasing v1.0.0

### ISSUE THREAD

**Issue by james-d-mitchell** [libsemigroups/HPCombi#27]
- [x] Set up the webpages
- [x] Fix the make install target
- [x] Finalise cmake stuff to check for flags and `__builtin_whatever`
- [x] release script
- [x] update the README (mentioning simde!)
- [x] update `BUILDING.md` + ~~merge it with `README.md`~~
- [x] make code coverage optional ~~and merge the branch~~

**Comment by hivert** [comment]
I just set up a web page on https://libsemigroups.github.io/HPCombi/ it still needs to be improved with some benchmark

**Comment by james-d-mitchell** [comment]
Nice one! I've made some more cleanups in the rc-v1.0.0 branch too, I think we should make release, maybe tomorrow if that's ok with you @hivert ?
