### ISSUE TITLE
Circle ci (arm jobs) no longer triggered by PRs

### ISSUE THREAD

**Issue by james-d-mitchell** [libsemigroups/HPCombi#40]
Maybe they never were, but I somehow remember it. Where have the circleci jobs gone? @reiniscirpons any insights?

**Comment by reiniscirpons** [comment]
Hi James, I've no idea. We do have a `.circleci` directory and I remember setting it up and testing it. But there is no corresponding workflow in the `.github/workflows` directory. Could this have to do with HPCombi changing organizations?

**Comment by james-d-mitchell** [comment]
I suspect it is because of the organization change, but I'm not sure, I have a vague memory that we knew that circleci wouldn't work anymore, but don't find any indication of that anywhere (i.e. comments or something that might be helpful).

**Comment by james-d-mitchell** [comment]
Resolved
